### ISSUE TITLE
Wrong values reported when reading from LOG-VOL

### ISSUE THREAD

**Issue by jeanbez** [DataLib-ECP/vol-log-based#12] opened 2021-12-21 04:48 UTC
While running in Summit and Cori with LOG-VOL I noticed that the reported read values are incorrect when compared to not using the VOL connector. It happened in sequential and parallel runs.

**Comment by khou2020** [comment] 2021-12-21 05:34
> While running in Summit and Cori with LOG-VOL I noticed that the reported read values are incorrect when compared to not using the VOL connector. It happened in sequential and parallel runs.

Can you share your application?
May I know your environment settings and steps to build it?
What is the HDF5 version used?
What is the logvol version used (commit)?

**Comment by jeanbez** [comment] 2021-12-21 05:38
The application is OpenPMD (). I added a small snippet to print the data that was read by each rank to be able to validate if the ADIOS, HDF5, and HDF5 with LOG-VOL versions were reading the data correctly. It turns out that the data reported when I use the LOG-VOL is very inconsistent with the one reported by HDF5 alone and with the one reported when using ADIOS. When I disable the environment variables, thus bypassing the LOG-VOL, the output matches. Thus, I believe we might have an issue when reading with that connector. 

I've shared the scripts I used to run on Summit by email. The used versions are:

```
LOG-VOL: commit 96afa55d98f3687ee95d342088509e32260af692
HDF5:    commit 48a05aa887ae7d18512756bf1eeb177e08d0feaf
OpenPMD: commit dd0abbc7506ef665ba4ae9bbfa618644ec8aa3be

bsub -Is -W 00:30 -nnodes 1 -P CSC300 $SHEL

git clone https://github.com/openPMD/openPMD-api
cd openPMD-api
mkdir build
cd build
export CC=$(which gcc)
export CXX=$(which g++)
cmake .. -DopenPMD_USE_MPI=ON -DopenPMD_USE_ADIOS2=OFF -DopenPMD_USE_HDF5=ON -DopenPMD_USE_ADIOS1=OFF -DopenPMD_USE_PYTHON=OFF -DCMAKE_CXX_STANDARD=14
make -j 6
```

You might need to provide the path to your HDF5 installation for CMake (`-DCMAKE_PREFIX_PATH=path/to/your/hdf5/install`). If you want to print the read data to compare, I'm sending the modified version of the benchmark file [examples/8b_benchmark_read_parallel.cpp](https://gist.github.com/jeanbez/a897f1d3bfc5095ed5a2da85e2240944)

**Comment by khou2020** [comment] 2021-12-21 06:28
Can you provide instruction to run the benchmark?

I ran it locally on a single process, but it didn't print the data read.
I overwrite example/8b_benchmark_read_parallel.cpp with the code you provided before build.

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ ./8a_benchmark_write_parallel
 memory at:    Main  VmSize:       43668 kB VmRSS:         18880 kB VmSwap:            0 kB

Global: [ 64 256 256 ]  Block: [ 64 32 32 ]   Unit: [ 1 8 8 ]
MPI Size: 1  mesh/particle ratio=1 UnBalance? 0  steps=1 multiBlock? 0
 memory at:  Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:    43668 kB VmRSS:         18880 kB VmSwap:            0 kB
 memory at:  ~Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:           45876 kB VmRSS:         32380 kB VmSwap:            0 kB
  [Writing: ../samples/8a_parallel_3Db_%07T.h5] took:0.489 seconds
     Writing: ../samples/8a_parallel_3Db_%07T.h5  From ProgStart in seconds 0.499

 memory at:  ~  Main  VmSize:      37196 kB VmRSS:         25652 kB VmSwap:            0 kB
  [  Main  ] took:0.49 seconds
       Main    From ProgStart in seconds 0.5

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ ./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
  fileBased
  Num Iterations in ../samples/8a_parallel_3Db_0000001.h5 : 1

===> rho meshExtent : ts=0 [64 256 256 ]
  Total Num iterations read: 1

  [Reading: ../samples/8a_parallel_3Db_0000001.h5] took:0.03 seconds.
         From ProgStart in seconds 0.04

  [  Main  ] took:0.031 seconds.
         From ProgStart in seconds 0.04

**Comment by jeanbez** [comment] 2021-12-21 07:16
Can you try running it with: `./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5 sy` ?

**Comment by khou2020** [comment] 2021-12-21 07:39
> Can you try running it with: `./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5 sy` ?

Same result.

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ ./8a_benchmark_write_parallel
 memory at:    Main  VmSize:       43668 kB VmRSS:         18852 kB VmSwap:            0 kB

Global: [ 64 256 256 ]  Block: [ 64 32 32 ]   Unit: [ 1 8 8 ]
MPI Size: 1  mesh/particle ratio=1 UnBalance? 0  steps=1 multiBlock? 0
 memory at:  Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:    43668 kB VmRSS:         18852 kB VmSwap:            0 kB
^[[A memory at:  ~Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:       45876 kB VmRSS:         32864 kB VmSwap:            0 kB
  [Writing: ../samples/8a_parallel_3Db_%07T.h5] took:0.519 seconds
     Writing: ../samples/8a_parallel_3Db_%07T.h5  From ProgStart in seconds 0.528

 memory at:  ~  Main  VmSize:      37196 kB VmRSS:         26136 kB VmSwap:            0 kB
  [  Main  ] took:0.52 seconds
       Main    From ProgStart in seconds 0.529

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ ./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5 sy
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
  fileBased
  Num Iterations in ../samples/8a_parallel_3Db_0000001.h5 : 1

===> rho meshExtent : ts=0 [64 256 256 ]
  Rank: 0 offset [ 0 0 0 ] count[ 64 1 256 ]
  [Col slice time:  rank 0 only] took:0.004 seconds.
         From ProgStart in seconds 0.046

  Total Num iterations read: 1

  [Reading: ../samples/8a_parallel_3Db_0000001.h5] took:0.037 seconds.
         From ProgStart in seconds 0.046

  [  Main  ] took:0.037 seconds.
         From ProgStart in seconds 0.046

**Comment by wkliao** [comment] 2021-12-21 08:15
Kai-yuan
The issue Jean Luca encountered is the read contents being incorrect,
not whether the read or write test program fails to run or not.

**Comment by khou2020** [comment] 2021-12-21 09:08
> Kai-yuan The issue Jean Luca encountered is the read contents being incorrect, not whether the read or write test program fails to run or not.

I have to reproduce it first before I can debug. I can run the test program but cannot reproduce the issue. I need to make sure we are using the same arguments and build configurations.

**Comment by khou2020** [comment] 2021-12-21 09:10
> Can you try running it with: `./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5 sy` ?

I ran it locally on 4 processes, it did not show any difference from the native VOL.
Can you try again using the latest commit?

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ source ~/logvol/dev/utils/h5lenv.sh
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ echo ${HDF5_VOL_CONNECTOR}
LOG under_vol=0;under_info={}
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mpiexec -np 4 ./8a_benchmark_write_parallel
 memory at:    Main  VmSize:       56804 kB VmRSS:         16716 kB VmSwap:            0 kB

Global: [ 256 256 256 ]  Block: [ 64 32 32 ]   Unit: [ 4 8 8 ]
MPI Size: 4  mesh/particle ratio=1 UnBalance? 0  steps=1 multiBlock? 0
 memory at:  Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:    56804 kB VmRSS:         16716 kB VmSwap:            0 kB
 memory at:  ~Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:           59528 kB VmRSS:         30700 kB VmSwap:            0 kB
  [Writing: ../samples/8a_parallel_3Db_%07T.h5] took:1.326 seconds
     Writing: ../samples/8a_parallel_3Db_%07T.h5  From ProgStart in seconds 1.36

 memory at:  ~  Main  VmSize:      37348 kB VmRSS:         25404 kB VmSwap:            0 kB
  [  Main  ] took:1.328 seconds
       Main    From ProgStart in seconds 1.361

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mpiexec -np 4 ./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5 sy
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
  Rank: 2 offset [ 0 2 0 ] count[ 256 1 256 ]
  Rank: 3 offset [ 0 3 0 ] count[ 256 1 256 ]
  Rank: 1 offset [ 0 1 0 ] count[ 256 1 256 ]
  fileBased
  Num Iterations in ../samples/8a_parallel_3Db_0000001.h5 : 1

===> rho meshExtent : ts=0 [256 256 256 ]
  Rank: 0 offset [ 0 0 0 ] count[ 256 1 256 ]
  [Col slice time: ] took:0.027 seconds.
         From ProgStart in seconds 0.097

  Total Num iterations read: 1

  [Reading: ../samples/8a_parallel_3Db_0000001.h5] took:0.066 seconds.
         From ProgStart in seconds 0.098

  [  Main  ] took:0.066 seconds.
         From ProgStart in seconds 0.098

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mv validate-rank-0.txt validate-rank-0.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mv validate-rank-1.txt validate-rank-1.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mv validate-rank-2.txt validate-rank-2.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mv validate-rank-3.txt validate-rank-3.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ unset HDF5_VOL_CONNECTOR
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ echo ${HDF5_VOL_CONNECTOR}

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mpiexec -np 4 ./8a_benchmark_write_parallel
 memory at:    Main  VmSize:       56804 kB VmRSS:         16144 kB VmSwap:            0 kB

Global: [ 256 256 256 ]  Block: [ 64 32 32 ]   Unit: [ 4 8 8 ]
MPI Size: 4  mesh/particle ratio=1 UnBalance? 0  steps=1 multiBlock? 0
 memory at:  Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:    56804 kB VmRSS:         16144 kB VmSwap:            0 kB
 memory at:  ~Writing: ../samples/8a_parallel_3Db_%07T.h5VmSize:           63600 kB VmRSS:         34872 kB VmSwap:            0 kB
  [Writing: ../samples/8a_parallel_3Db_%07T.h5] took:2.808 seconds
     Writing: ../samples/8a_parallel_3Db_%07T.h5  From ProgStart in seconds 2.841

 memory at:  ~  Main  VmSize:      42024 kB VmRSS:         30152 kB VmSwap:            0 kB
  [  Main  ] took:2.81 seconds
       Main    From ProgStart in seconds 2.842

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ mpiexec -np 4 ./8b_benchmark_read_parallel ../samples/8a_parallel_3Db_0000001.h5 sy
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
Series constructor called with explicit iteration suggests loading a single file with groupBased iteration encoding. Loaded file is fileBased.
  Rank: 2 offset [ 0 2 0 ] count[ 256 1 256 ]
  Rank: 3 offset [ 0 3 0 ] count[ 256 1 256 ]
  fileBased
  Num Iterations in ../samples/8a_parallel_3Db_0000001.h5 : 1

===> rho meshExtent : ts=0 [256 256 256 ]
  Rank: 1 offset [ 0 1 0 ] count[ 256 1 256 ]
  Rank: 0 offset [ 0 0 0 ] count[ 256 1 256 ]
  [Col slice time: ] took:0.002 seconds.
         From ProgStart in seconds 0.061

  Total Num iterations read: 1

  [Reading: ../samples/8a_parallel_3Db_0000001.h5] took:0.029 seconds.
         From ProgStart in seconds 0.061

  [  Main  ] took:0.029 seconds.
         From ProgStart in seconds 0.061

khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ diff validate-rank-0.txt validate-rank-0.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ diff validate-rank-1.txt validate-rank-1.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ diff validate-rank-2.txt validate-rank-2.logvol
khl7265@DESKTOP-4P9VSI7:~/openPMD-api/build/bin$ diff validate-rank-3.txt validate-rank-3.logvol

**Comment by jeanbez** [comment] 2021-12-21 22:14
@khou2020 I've pulled the last changes and ran locally, in Summit, and in Cori, and it now seems to work as expected. Thanks for the update!

**Comment by wkliao** [comment] 2021-12-21 22:43
@jeanbez 
Can you test other cases and let us know if they passed?
So, we can close this ticket and move on to check the strange
behavior about the write/read amounts and number of
write/read calls you mentioned last week.

**Comment by brtnfld** [comment] 2021-12-31 17:08
I can verify that it was getting incorrect values with hdf5-iotest, and with the current version of the LOG VOL, the values are now correct.

**Closed** 2021-12-31 18:22 UTC
